language: clojure
dist: noble

addons:
      apt:
        packages:
          - gzip


jdk: openjdk17

rvm:
  - 2.6

stages:
      - name: test
        if: branch = develop
      - name: publish
        if: tag IS present

cache: bundler

jobs:
      include:
        - stage: build
          name: "Build & Test"
          script:
            - lein test
        - stage: test
          install:
            - lein deps
            - lein pom
          script:
            - lein test
        - stage: publish
          install:
            - lein deps
            - lein pom
          script: lein test
          deploy:
            provider: script
            script: lein deploy
            cleanup: false
            on:
              tags: true
              all_branches: true
